const CACHE_NAME = 'arpa-luna-v73';

// Only cache small essential files + small photos
// Large photos (>2MB) are excluded from pre-cache to avoid install failures
// They will still load from network and get cached on demand
const ASSETS = [
  './',
  'index.html',
  'style.css',
  'app.js',
  'manifest.json',
  'icon-arpa-192.png',
  'icon-arpa-512.png',
  'assets/animations/luna_moon.json',
  'assets/daa7254c-65ac-4c99-a41c-bb63cdecec96-1e8067c.jpg',
              'assets/arpa_memory_1.jpg',
  'assets/arpa_memory_2.jpg',
  'assets/arpa_memory_3.jpg',
  'assets/arpa_memory_4.jpg',
  'assets/arpa_memory_5.jpg',
  'assets/arpa_memory_6.jpg',
  'assets/arpa_memory_7.jpg',
  'assets/arpa_memory_8.jpg',
  'assets/arpa_memory_9.jpg',
  'assets/arpa_memory_10.jpg',
  'assets/arpa_memory_11.jpg',
  'assets/arpa_memory_12.jpg',
  'assets/arpa_memory_13.jpg',
  'assets/arpa_memory_14.jpg',
  'assets/arpa_memory_15.jpg',
  'assets/arpa_memory_16.jpg',
  'assets/arpa_memory_17.jpg',
  'assets/arpa_memory_18.jpg',
  'assets/arpa_memory_19.jpg',
  'assets/arpa_memory_20.jpg',
  'assets/arpa_memory_21.jpg',
  'assets/arpa_memory_22.jpg',
  'assets/arpa_memory_23.jpg',
  'assets/arpa_memory_24.jpg',
  'assets/arpa_memory_25.jpg',
  'assets/arpa_memory_26.jpg',
  'assets/arpa_memory_27.jpg',
  'assets/arpa_memory_28.jpg',
  'assets/arpa_memory_29.jpg',
  'assets/arpa_memory_30.jpg',
  'assets/arpa_memory_31.jpg',
  'assets/arpa_memory_32.jpg',
  'assets/arpa_memory_33.jpg',
  'assets/arpa_memory_34.jpg',
  'assets/arpa_memory_35.jpg',
  'assets/arpa_memory_36.jpg',
  'assets/arpa_memory_37.jpg',
  'assets/arpa_memory_38.jpg',
  'assets/arpa_memory_39.jpg',
  'assets/arpa_memory_40.jpg',
  'assets/arpa_memory_41.jpg',
  'assets/arpa_memory_42.jpg',
  'assets/arpa_memory_43.jpg',
  'assets/arpa_memory_44.jpg',
  'assets/arpa_memory_45.jpg',
  'assets/arpa_memory_46.jpg',
  'assets/arpa_memory_47.jpg',
  'assets/arpa_memory_48.jpg',
  'assets/arpa_memory_49.jpg',
  'assets/arpa_memory_50.jpg',
  'assets/arpa_memory_51.jpg',
  'assets/arpa_memory_52.jpg',
  'assets/arpa_memory_53.jpg',
  'assets/arpa_memory_54.jpg',
  'assets/arpa_memory_55.jpg',
  'assets/arpa_memory_56.jpg',
  'assets/arpa_memory_57.jpg',
  'assets/arpa_memory_58.jpg',
  'assets/arpa_memory_59.jpg',
  'assets/arpa_memory_60.jpg',
  'assets/arpa_memory_61.jpg',
  'assets/arpa_memory_62.jpg',
  'assets/arpa_memory_63.jpg',
  'assets/arpa_memory_64.jpg',
  'assets/arpa_memory_65.jpg',
  'assets/arpa_memory_66.jpg',
  'assets/arpa_memory_67.jpg',
  'assets/arpa_memory_68.jpg',
  'assets/arpa_memory_69.jpg',
  'assets/arpa_memory_70.jpg',
  'assets/arpa_memory_71.jpg',
  'assets/arpa_memory_72.jpg',
  'assets/arpa_memory_73.jpg',
  'assets/arpa_memory_74.jpg',
  'assets/arpa_memory_75.jpg',
  'assets/arpa_memory_76.jpg',
  'assets/arpa_memory_77.jpg',
  'assets/arpa_memory_78.jpg',
  'assets/arpa_memory_79.jpg',
  'assets/arpa_memory_80.jpg',
  'assets/arpa_memory_81.jpg',
  'assets/arpa_memory_82.jpg',
  'assets/arpa_memory_83.jpg',
  'assets/arpa_memory_84.jpg',
  'assets/arpa_memory_85.jpg',
  'assets/arpa_memory_86.jpg',
  'assets/arpa_memory_87.jpg',
  'assets/arpa_memory_88.jpg',
  'assets/arpa_memory_89.jpg',
  'assets/arpa_memory_90.jpg',
  'assets/arpa_memory_91.jpg',
  'assets/arpa_memory_92.jpg',
  'assets/arpa_memory_93.jpg',
  'assets/arpa_memory_94.jpg',
  'assets/arpa_memory_95.jpg',
  'assets/arpa_memory_96.jpg',
  'assets/arpa_memory_97.jpg',
  'assets/arpa_memory_98.jpg',
  'assets/arpa_memory_99.jpg',
  'assets/arpa_memory_100.jpg',
  'assets/arpa_memory_101.jpg',
  'assets/arpa_memory_102.jpg',
  'assets/arpa_memory_103.jpg',
  'assets/arpa_memory_104.jpg',
  'assets/arpa_memory_105.jpg',
  'assets/arpa_memory_106.jpg',
  'assets/arpa_memory_107.jpg',
  'assets/arpa_memory_108.jpg',
  'assets/arpa_memory_109.jpg',
  'assets/arpa_memory_110.jpg',
  'assets/arpa_memory_111.jpg',
  'assets/arpa_memory_112.jpg',
  'assets/arpa_memory_113.jpg',
  'assets/arpa_memory_114.jpg',
  'assets/arpa_memory_115.jpg',
  'assets/arpa_memory_116.jpg',
  'assets/arpa_memory_117.jpg',
  'assets/arpa_memory_118.jpg',
  'assets/arpa_memory_119.jpg',
  'assets/arpa_memory_120.jpg',
  'assets/arpa_memory_121.jpg',
  'assets/arpa_memory_122.jpg',
  'assets/arpa_memory_123.jpg',
  'assets/arpa_memory_124.jpg',
  'assets/arpa_memory_125.jpg',
  'assets/arpa_memory_126.jpg',
  'assets/arpa_memory_127.jpg',
  'assets/arpa_memory_128.jpg',
  'assets/arpa_memory_129.jpg',
  'assets/arpa_memory_130.jpg',
  'assets/arpa_memory_131.jpg',
  'assets/arpa_memory_132.jpg',
  'assets/arpa_memory_133.jpg',
  'assets/arpa_memory_134.jpg',
  'assets/arpa_memory_135.jpg',
  'assets/arpa_memory_136.jpg',
  'assets/arpa_memory_137.jpg',
  'assets/arpa_memory_138.jpg',
  'assets/arpa_memory_139.jpg',
  'assets/arpa_memory_140.jpg',
  'assets/arpa_memory_141.jpg',
  'assets/arpa_memory_142.jpg',
  'assets/arpa_memory_143.jpg',
  'assets/arpa_memory_144.jpg',
  'assets/arpa_memory_145.jpg',
  'assets/arpa_memory_146.jpg',
  'assets/arpa_memory_147.jpg',
  'assets/arpa_memory_148.jpg',
  'assets/arpa_memory_149.jpg',
  'assets/arpa_memory_150.jpg',
  'assets/arpa_memory_151.jpg',
  'assets/arpa_memory_152.jpg',
  'assets/arpa_memory_153.jpg',
  'assets/arpa_memory_154.jpg',
  'assets/arpa_memory_155.jpg',
  'assets/arpa_memory_156.jpg',
  'assets/arpa_memory_157.jpg',
  'assets/arpa_memory_158.jpg',
  'assets/arpa_memory_159.jpg',
  'assets/arpa_memory_160.jpg',
  'assets/arpa_memory_161.jpg',
  'assets/arpa_memory_162.jpg',
  'assets/arpa_memory_163.jpg',
  'assets/arpa_memory_164.jpg',
  'assets/arpa_memory_165.jpg',
  'assets/arpa_memory_166.jpg',
  'assets/arpa_memory_167.jpg',
  'assets/arpa_memory_168.jpg',
  'assets/arpa_memory_169.jpg',
  'assets/arpa_memory_170.jpg',
  'assets/arpa_memory_171.jpg',
  'assets/arpa_memory_172.jpg',
  'assets/arpa_memory_173.jpg',
  'assets/arpa_memory_174.jpg',
  'assets/arpa_memory_175.jpg',
  'assets/arpa_memory_176.jpg',
  'assets/arpa_memory_177.jpg',
  'assets/arpa_memory_178.jpg',
  'assets/arpa_memory_179.jpg',
  'assets/arpa_memory_180.jpg',
  'assets/arpa_memory_181.jpg',
  'assets/arpa_memory_182.jpg',
  'assets/arpa_memory_183.jpg',
  'assets/arpa_memory_184.jpg',
  'assets/arpa_memory_185.jpg',
  'assets/arpa_memory_186.jpg',
  'assets/arpa_memory_187.jpg',
  'assets/arpa_memory_188.jpg',
  'assets/arpa_memory_189.jpg',
  'assets/arpa_memory_190.jpg',
  'assets/arpa_memory_191.jpg',
  'assets/arpa_memory_192.jpg',
  'assets/arpa_memory_193.jpg',
  'assets/arpa_memory_194.jpg',
  'assets/arpa_memory_195.jpg',
  'assets/arpa_memory_196.jpg',
  'assets/arpa_memory_197.jpg',
  'assets/arpa_memory_198.jpg',
  'assets/arpa_memory_199.jpg',
  'assets/arpa_memory_200.jpg',
  'assets/arpa_memory_201.jpg',
  'assets/arpa_memory_202.jpg',
  'assets/arpa_memory_203.jpg',
  'assets/arpa_memory_204.jpg',
  'assets/arpa_memory_205.jpg',
  'assets/arpa_memory_206.jpg',
  'assets/arpa_memory_207.jpg',
  'assets/arpa_memory_208.jpg',
  'assets/arpa_memory_209.jpg',
  'assets/arpa_memory_210.jpg',
  'assets/arpa_memory_211.jpg',
  'assets/arpa_memory_212.jpg',
  'assets/arpa_memory_213.jpg',
  'assets/arpa_memory_214.jpg',
  'assets/arpa_memory_215.jpg',
  'assets/arpa_memory_216.jpg',
  'assets/arpa_memory_217.jpg',
  'assets/arpa_memory_218.jpg',
  'assets/arpa_memory_219.jpg',
  'assets/arpa_memory_220.jpg',
  'assets/arpa_memory_221.jpg',
  'assets/arpa_memory_222.jpg',
  'assets/arpa_memory_223.jpg',
  'assets/arpa_memory_224.jpg',
  'assets/arpa_memory_225.jpg',
  'assets/arpa_memory_226.jpg',
  'assets/arpa_memory_227.jpg',
  'assets/arpa_memory_228.jpg',
  'assets/arpa_memory_229.jpg',
  'assets/arpa_memory_230.jpg',
  'assets/arpa_memory_231.jpg',
  'assets/arpa_memory_232.jpg',
  'assets/arpa_memory_233.jpg',
  'assets/arpa_memory_234.jpg',
  'assets/arpa_memory_235.jpg',
  'assets/arpa_memory_236.jpg',
  'assets/arpa_memory_237.jpg',
  'assets/arpa_memory_238.jpg',
  'assets/arpa_memory_239.jpg',
  'assets/arpa_memory_240.jpg',
  'assets/arpa_memory_241.jpg',
  'assets/arpa_memory_242.jpg',
  'assets/arpa_memory_243.jpg',
  'assets/arpa_memory_244.jpg',
  'assets/arpa_memory_245.jpg',
  'assets/arpa_memory_246.jpg',
  'assets/arpa_memory_247.jpg',
  'assets/arpa_memory_248.jpg',
  'assets/arpa_memory_249.jpg',
  'assets/arpa_memory_250.jpg',
  'assets/arpa_memory_251.jpg',
  'assets/arpa_memory_252.jpg',
  'assets/arpa_memory_253.jpg',
  'assets/arpa_memory_254.jpg',
  'assets/arpa_memory_255.jpg',
  'assets/arpa_memory_256.jpg',
  'assets/arpa_memory_257.jpg',
  'assets/arpa_memory_258.jpg',
  'assets/arpa_memory_259.jpg',
  'assets/arpa_memory_260.jpg',
  'assets/arpa_memory_261.jpg',
  'assets/arpa_memory_262.jpg',
  'assets/arpa_memory_263.jpg',
  'assets/arpa_memory_264.jpg',
  'assets/arpa_memory_265.jpg',
  'assets/arpa_memory_266.jpg',
  'assets/arpa_memory_267.jpg',
  'assets/arpa_memory_268.jpg',
  'assets/arpa_memory_269.jpg',
  'assets/arpa_memory_270.jpg',
  'assets/arpa_memory_271.jpg',
  'assets/arpa_memory_272.jpg',
  'assets/arpa_memory_273.jpg',
  'assets/arpa_memory_274.jpg',
  'assets/arpa_memory_275.jpg',
  'assets/arpa_memory_276.jpg',
  'assets/arpa_memory_277.jpg',
  'assets/arpa_memory_278.jpg',
  'assets/arpa_memory_279.jpg',
  'assets/arpa_memory_280.jpg',
  'assets/arpa_memory_281.jpg',
  'assets/arpa_memory_282.jpg',
  'assets/arpa_memory_283.jpg',
  'assets/arpa_memory_284.jpg',
  'assets/arpa_memory_285.jpg',
  'assets/arpa_memory_286.jpg',
  'assets/arpa_memory_287.jpg',
  'assets/arpa_memory_288.jpg',
  'assets/arpa_memory_289.jpg',
  'assets/arpa_memory_290.jpg',
  'assets/arpa_memory_291.jpg',
  'assets/arpa_memory_292.jpg',
  'assets/arpa_memory_293.jpg',
  'assets/arpa_memory_294.jpg',
  'assets/arpa_memory_295.jpg',
  'assets/arpa_memory_296.jpg',
  'assets/arpa_memory_297.jpg',
  'assets/arpa_memory_298.jpg',
  'assets/arpa_memory_299.jpg',
  'assets/arpa_memory_300.jpg',
  'assets/arpa_memory_301.jpg',
  'assets/arpa_memory_302.jpg',
  'assets/arpa_memory_303.jpg',
  'assets/arpa_memory_304.jpg',
  'assets/arpa_memory_305.jpg',
  'assets/arpa_memory_306.jpg',
  'assets/arpa_memory_307.jpg',
  'assets/arpa_memory_308.jpg',
  'assets/arpa_memory_309.jpg',
  'assets/arpa_memory_310.jpg',
  'assets/arpa_memory_311.jpg',
  'assets/arpa_memory_312.jpg',
  'assets/arpa_memory_313.jpg',
  'assets/arpa_memory_314.jpg',
  'assets/arpa_memory_315.jpg',
  'assets/arpa_memory_316.jpg',
  'assets/arpa_memory_317.jpg',
  'assets/arpa_memory_318.jpg',
  'assets/arpa_memory_319.jpg',
  'assets/arpa_memory_320.jpg',
  'assets/arpa_memory_321.jpg',
  'assets/arpa_memory_322.jpg',
  'assets/arpa_memory_323.jpg',
  'assets/arpa_memory_324.jpg',
  'assets/arpa_memory_325.jpg',
  'assets/arpa_memory_326.jpg',
  'assets/arpa_memory_327.jpg',
  'assets/arpa_memory_328.jpg',
  'assets/arpa_memory_329.jpg',
  'assets/arpa_memory_330.jpg',
  'assets/arpa_memory_331.jpg',
  'assets/arpa_memory_332.jpg',
  'assets/arpa_memory_333.jpg',
  'assets/arpa_memory_334.jpg',
  'assets/arpa_memory_335.jpg',
  'assets/arpa_memory_336.jpg',
  'assets/arpa_memory_337.jpg',
  'assets/arpa_memory_338.jpg',
  'assets/arpa_memory_339.jpg',
  'assets/arpa_memory_340.jpg',
  'assets/arpa_memory_341.jpg',
  'assets/arpa_memory_342.jpg',
  'assets/arpa_memory_343.jpg',
  'assets/arpa_memory_344.jpg',
  'assets/arpa_memory_345.jpg',
  'assets/arpa_memory_346.jpg',
  'assets/arpa_memory_347.jpg',
  'assets/arpa_memory_348.jpg',
  'assets/arpa_memory_349.jpg',
  'assets/arpa_memory_350.jpg',
  'assets/arpa_memory_351.jpg',
  'assets/arpa_memory_352.jpg',
  'assets/arpa_memory_353.jpg',
  'assets/arpa_memory_354.jpg',
  'assets/arpa_memory_355.jpg',
  'assets/arpa_memory_356.jpg',
  'assets/arpa_memory_357.jpg',
  'assets/arpa_memory_358.jpg',
  'assets/arpa_memory_359.jpg',
  'assets/arpa_memory_360.jpg',
  'assets/arpa_memory_361.jpg',
  'assets/arpa_memory_362.jpg',
  'assets/arpa_memory_363.jpg',
  'assets/arpa_memory_364.jpg',
  'assets/arpa_memory_365.jpg',
  'assets/arpa_memory_366.jpg'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      // Use Promise.allSettled so one failed asset doesn't break the whole install
      return Promise.allSettled(
        ASSETS.map(asset => cache.add(asset).catch(err => {
          console.warn('Failed to cache:', asset, err);
        }))
      );
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  const isIndex = url.pathname === '/' || url.pathname.endsWith('index.html') || url.pathname.endsWith('/arpa-luna/');

  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((cachedResponse) => {
      if (cachedResponse) return cachedResponse;

      if (isIndex) {
        return caches.match('index.html').then(response => response || fetch(event.request));
      }

      // Fetch from network and cache for future offline use
      return fetch(event.request).then(response => {
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(event.request, clone));
        }
        return response;
      });
    }).catch(() => {
      if (isIndex) return caches.match('index.html');
    })
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then(windowClients => {
      for (let client of windowClients) {
        if (client.url.includes('arpa-luna') && 'focus' in client) return client.focus();
      }
      if (clients.openWindow) return clients.openWindow('./');
    })
  );
});











